#!/usr/bin/env sh

# Usage Scenario: Launch oneagentd in VeFaaS environment from local bundle, and launch oneagent based on built-in CR
# Convention Directory Structure Example:
#   <bundle>/
#     o11yagentd/
#       o11yagentd
#       o11yagentctl
#       data/cr/default.yaml
#     scripts/
#       o11yagentd_vefaas.sh
#
# Examples:
#   1) Default install to <bundle>/o11yagentd:
#      APP_REGION=cn-beijing \
#      sh <bundle>/scripts/o11yagentd_vefaas.sh start
#
#   2) Explicitly specify download.registry (override default generation rule):
#      APP_REGION=cn-beijing \
#      sh <bundle>/scripts/o11yagentd_vefaas.sh start \
#        --download.registry https://o11yagent-registry-cn-beijing.ivolces.com
#
#   3) Override install_dir for testing (must ensure data/cr etc. exist):
#      APP_REGION=cn-beijing \
#      sh <bundle>/scripts/o11yagentd_vefaas.sh start \
#        --install_dir /tmp/o11yagent_test
#
# Features:
#   1) Automatically locate bundle root, default install dir is <bundle>/o11yagentd
#   2) Generate config based on bundle's o11yagentd to <install_dir>/conf/o11yagentd.yaml:
#        - deploy_env=vefaas
#        - credentials.region = APP_REGION env
#        - site default volcengine (override via --site)
#        - remote_manager.address use 127.0.0.1 placeholder
#        - download.registry: if not specified via --download.registry, generated by default_registry_address_url
#        - api_server.address = unix://<install_dir>/sock/o11yagentd.sock
#   3) Start <bundle>/o11yagentd/o11yagentd start --conf-dir <install_dir>/conf in foreground via exec
#      (The script process becomes oneagentd process, no sock probe performed)
#   5) Network independent; launch oneagent based on <install_dir>/data/cr/default.yaml
#        - Optional param --cr.registry=file:///abs/path overrides spec.registry in CR

set -e

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
BUNDLE_DIR=$(cd "${SCRIPT_DIR}/.." && pwd)
BUNDLE_O11YAGENTD_DIR="${BUNDLE_DIR}/o11yagentd"

DEFAULT_SITE="volcengine"
DEFAULT_INSTALL_DIR="${BUNDLE_O11YAGENTD_DIR}"
DEFAULT_O11YAGENTD_DISK_IO_THROUGHPUT_LIMIT="51200000"

print_usage() {
    cat <<EOF
Usage:
  sh $0 start [options]

Options:
  --site SITE                 站点, 默认: ${DEFAULT_SITE}
  --control_plane_region R    控制平面 Region, 默认等于 APP_REGION (部分 Region 会内部映射)
  --registry_env ENV          registry 环境, 如 boe, 会作为 -boe 拼接到域名中
  --inner                     使用内部域名后缀, 对应域名中的 -inner 片段
  --download.registry URL     显式覆盖下载 registry 地址
  --install_dir DIR           oneagentd 工作目录, 默认: ${DEFAULT_INSTALL_DIR}
  --cr.registry FILE_URL      覆盖 CR 中 spec.registry (file:// 绝对路径)

Environment:
  APP_REGION                  必填, 作为 region 传入并生成 download.registry, 同时写入 credentials.region
EOF
}

# Reuse download.registry generation rules from oneagentd.sh
default_registry_address_url() {
    site="$1"
    region="$2"
    control_plane_region="$3"
    registry_env="$4"
    inner="$5"

    registry_region="${control_plane_region}"
    url=""

    case "${site}" in
        "volcengine")
            case "${registry_region}" in
                "cn-north-1-dedicated")
                    url="https://o11yagent-registry${registry_env}-${registry_region}.dualstack.cn-beijing.tos.volces.com"
                ;;
                "cn-guilin-boe")
                    registry_region="cn-boe"
                    if [ "${region}" = "cn-chengdu-sdv" ]; then
                        url="https://o11yagent-registry${registry_env}-${registry_region}.tos-${registry_region}${inner}.volces.com"
                    fi
                ;;
            esac
            if [ "${url}" = "" ]; then
                url="https://o11yagent-registry${registry_env}-${registry_region}.tos-${registry_region}${inner}.ivolces.com"
            fi
        ;;
        "byteplus")
            case "${registry_region}" in
                "cn-beijing" | "cn-shanghai" | "cn-guangzhou")
                    url="https://o11yagent-registry${registry_env}-${registry_region}-${site}.tos-${registry_region}${inner}.ibytepluses.com.cn"
                ;;
                "cn-hongkong" | "ap-southeast-1" | "ap-southeast-3")
                    url="https://o11yagent-registry${registry_env}-${registry_region}.tos-${registry_region}${inner}.ibytepluses.com"
                ;;
            esac
            if [ "${url}" = "" ]; then
                url="https://o11yagent-registry${registry_env}-${registry_region}-${site}.tos-${registry_region}${inner}.ibytepluses.com"
            fi
        ;;
        * )
            echo "unsupported site: ${site}" >&2
            exit 1
        ;;
    esac

    echo "${url}"
}

default_remote_manager_url() {
    site="$1"
    control_plane_region="$2"
    registry_env="$3"
    url=""

    case "${site}" in
        "volcengine")
            case "${control_plane_region}" in
                "cn-north-1-dedicated")
                    url="https://o11yagent-platform${registry_env}.cloudmonitor.${control_plane_region}.inner.ivolces.com"
                ;;
                *)
                    url="https://o11yagent-platform${registry_env}.cloudmonitor.${control_plane_region}.ivolces.com"
                ;;
            esac
        ;;
        "byteplus")
            case "${control_plane_region}" in
                "cn-beijing" | "cn-shanghai" | "cn-guangzhou")
                    url="https://o11yagent-platform${registry_env}.cloudmonitor.${control_plane_region}.ivolces.com"
                ;;
                *)
                    url="https://o11yagent-platform${registry_env}.cloudmonitor.${control_plane_region}.ibytepluses.com"
                ;;
            esac
        ;;
        * )
            echo "unsupported site: ${site}"
            exit 1
        ;;
    esac

    echo "${url}"
}

default_self_monitor_url() {
    region="$1"
    url=""
    case "${region}" in
        "cn-taiwan-boe")
            url="http://100.96.3.238/v2/write"
        ;;
        "cn-chongqing-sdv")
            url="http://100.96.3.248/v2/write"
        ;;
        "cn-nanjing-bbit")
            url="http://100.96.3.235/v2/write"
        ;;
        "cn-chengdu-sdv")
            url="http://100.96.7.224/v2/write"
        ;;
        "cn-ningbo-sdv")
            # No non-inner url in original script
        ;;
        "cn-guilin-boe")
            url="http://ops-tsdb.cloudmonitor.boe-stable.ivolces.com/v2/write"
        ;;
        "cn-beijing")
            url="http://ops-tsdb.cloudmonitor.cn-beijing.ivolces.com/v2/write"
        ;;
        "cn-shanghai")
            url="http://ops-tsdb.cloudmonitor.cn-shanghai.ivolces.com/v2/write"
        ;;
        "cn-guangzhou")
            url="http://ops-tsdb.cloudmonitor.cn-guangzhou.ivolces.com/v2/write"
        ;;
        "ap-southeast-1")
            url="http://ops-tsdb.cloudmonitor.ap-southeast-1.ivolces.com/v2/write"
        ;;
        "cn-beijing2")
            url="http://ops-tsdb.cloudmonitor.cn-beijing2.ivolces.com/v2/write"
        ;;
        "cn-datong")
            url="http://ops-tsdb.cloudmonitor.cn-datong.ivolces.com/v2/write"
        ;;
        "cn-beijing-selfdrive")
            url="http://ops-tsdb.cloudmonitor.cn-beijing-selfdrive.ivolces.com/v2/write"
        ;;
        "cn-hongkong")
            url="http://ops-tsdb.cloudmonitor.cn-hongkong.ivolces.com/v2/write"
        ;;
        "cn-wulanchabu")
            url="http://ops-tsdb.cloudmonitor.cn-wulanchabu.ivolces.com/v2/write"
        ;;
        "cn-beijing-autodriving")
            url="http://ops-tsdb.cloudmonitor.cn-beijing-autodriving.ivolces.com/v2/write"
        ;;
        "ap-southeast-2")
            url="http://ops-tsdb.cloudmonitor.ap-southeast-2.ivolces.com/v2/write"
        ;;
    esac

    if [ "${url}" = "" ]; then
        url="http://ops-tsdb.cloudmonitor.${region}.ivolces.com/v2/write"
    fi
    echo "${url}"
}

# Generate o11yagentd.yaml to <install_dir>/conf/
# Args: $1=o11y_dir $2=install_dir $3=site $4=region $5=download_registry $6=remote_manager_address $7=api_sock $8=disk_io_throughput_limit $9=self_telemetry_url
generate_config() {
    o11y_dir="$1"
    install_dir="$2"
    site="$3"
    region="$4"
    download_registry="$5"
    remote_manager_address="$6"
    api_sock="$7"
    disk_io_throughput_limit="$8"
    self_telemetry_url="$9"


    conf_dir="${install_dir}/conf"

    cd "${o11y_dir}"

    if [ ! -f "./o11yagentd" ]; then
        echo "ERROR: o11yagentd binary not found in ${o11y_dir}" >&2
        exit 1
    fi

    chmod +x ./o11yagentd || true

    rm -f o11yagentd.yaml

    ./o11yagentd gen-config \
        --install_dir="${install_dir}" \
        --site="${site}" \
        --deploy_env="vefaas" \
        --credentials.service="cloudmonitor" \
        --credentials.region="${region}" \
        --download.registry="${download_registry}" \
        --remote_manager.address="${remote_manager_address}" \
        --api_server.address="unix://${api_sock}" \
        --limiter.disk_io_throughput="${disk_io_throughput_limit}" \
        --self_telemetry.enable=true \
        --self_telemetry.remote_url="${self_telemetry_url}"

    if [ ! -f "o11yagentd.yaml" ]; then

        echo "ERROR: failed to generate o11yagentd.yaml" >&2
        exit 1
    fi

    mkdir -p "${conf_dir}"
    rm -f "${conf_dir}/o11yagentd.yaml"
    cp "o11yagentd.yaml" "${conf_dir}/o11yagentd.yaml"
}

# Optional: Override spec.registry in local CR
update_cr_registry_if_needed() {
    cr_registry="$1"
    install_dir="$2"

    if [ -z "${cr_registry}" ]; then
        return 0
    fi

    case "${cr_registry}" in
        file:///*)
            ;;
        *)
            echo "ERROR: --cr.registry must be an absolute file:// path, got: ${cr_registry}" >&2
            exit 1
            ;;
    esac

    cr_file="${install_dir}/data/cr/default.yaml"

    if [ ! -f "${cr_file}" ]; then
        echo "WARN: CR file not found at ${cr_file}, skip updating registry" >&2
        return 0
    fi

    tmp_file="${cr_file}.tmp.$$"
    if sed "s/^[[:space:]]*registry:.*/  registry: ${cr_registry}/" "${cr_file}" > "${tmp_file}"; then
        mv "${tmp_file}" "${cr_file}"
        echo "Updated CR registry to ${cr_registry} in ${cr_file}"
    else
        echo "WARN: failed to update CR registry in ${cr_file}" >&2
        rm -f "${tmp_file}"
    fi
}


# -------------------- Main Flow --------------------

if [ "$#" -lt 1 ]; then
    print_usage
    exit 1
fi

cmd="$1"
shift

case "${cmd}" in
    start)
        ;;
    -h|--help|help)
        print_usage
        exit 0
        ;;
    *)
        echo "Unsupported command: ${cmd}" >&2
        print_usage
        exit 1
        ;;
esac

SITE="${DEFAULT_SITE}"
CONTROL_PLANE_REGION=""
REGISTRY_ENV_SUFFIX=""
INNER_SUFFIX=""
DOWNLOAD_REGISTRY=""
INSTALL_DIR="${DEFAULT_INSTALL_DIR}"
CR_REGISTRY=""
O11YAGENTD_DISK_IO_THROUGHPUT_LIMIT="${DEFAULT_O11YAGENTD_DISK_IO_THROUGHPUT_LIMIT}"

while [ "$#" -gt 0 ]; do
    case "$1" in
        --site)
            shift
            SITE="$1"
            ;;
        --control_plane_region)
            shift
            CONTROL_PLANE_REGION="$1"
            ;;
        --disk_io_throughput_limit)
            shift
            O11YAGENTD_DISK_IO_THROUGHPUT_LIMIT="$1"
            ;;
        --registry_env)
            shift
            if [ -n "$1" ]; then
                REGISTRY_ENV_SUFFIX="-$1"
            fi
            ;;
        --inner)
            INNER_SUFFIX="-inner"
            ;;
        --download.registry)
            shift
            DOWNLOAD_REGISTRY="$1"
            ;;
        --install_dir)
            shift
            INSTALL_DIR="$1"
            ;;
        --cr.registry)
            shift
            CR_REGISTRY="$1"
            ;;
        -h|--help|help)
            print_usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            print_usage
            exit 1
            ;;
    esac
    shift
done

if [ -z "${APP_REGION}" ]; then
    echo "APP_REGION environment variable is required for VeFaaS deployment" >&2
    exit 1
fi
REGION="${APP_REGION}"

# Default control_plane_region=APP_REGION, map for some regions
if [ -z "${CONTROL_PLANE_REGION}" ]; then
    CONTROL_PLANE_REGION="${REGION}"
    case "${REGION}" in
        "cn-chengdu-sdv")
            CONTROL_PLANE_REGION="cn-guilin-boe"
            ;;
    esac
fi

# INSTALL_DIR supports relative path, relative to bundle root
case "${INSTALL_DIR}" in
    /*)
        ;;
    *)
        INSTALL_DIR="${BUNDLE_DIR}/${INSTALL_DIR}"
        ;;
esac

CONF_DIR="${INSTALL_DIR}/conf"
SOCK_DIR="${INSTALL_DIR}/sock"
SOCK_FILE="${SOCK_DIR}/o11yagentd.sock"

mkdir -p "${CONF_DIR}" "${SOCK_DIR}"

if [ ! -d "${BUNDLE_O11YAGENTD_DIR}" ]; then
    echo "ERROR: bundle o11yagentd directory not found at ${BUNDLE_O11YAGENTD_DIR}" >&2
    exit 1
fi

if [ ! -f "${BUNDLE_O11YAGENTD_DIR}/o11yagentd" ]; then
    echo "ERROR: o11yagentd binary not found at ${BUNDLE_O11YAGENTD_DIR}/o11yagentd" >&2
    exit 1
fi

if [ ! -f "${BUNDLE_O11YAGENTD_DIR}/o11yagentctl" ]; then
    echo "ERROR: o11yagentctl binary not found at ${BUNDLE_O11YAGENTD_DIR}/o11yagentctl" >&2
    exit 1
fi

chmod +x "${BUNDLE_O11YAGENTD_DIR}/o11yagentd" "${BUNDLE_O11YAGENTD_DIR}/o11yagentctl" || true

# Calculate download.registry placeholder address
if [ -z "${DOWNLOAD_REGISTRY}" ]; then
    DOWNLOAD_REGISTRY=$(default_registry_address_url "${SITE}" "${REGION}" "${CONTROL_PLANE_REGION}" "${REGISTRY_ENV_SUFFIX}" "${INNER_SUFFIX}")
fi

# Calculate remote.manager.address placeholder address
REMOTE_MANAGER_ADDRESS=$(default_remote_manager_url "${SITE}" "${CONTROL_PLANE_REGION}" "${REGISTRY_ENV_SUFFIX}" "${INNER_SUFFIX}")

# Calculate self telemetry url
SELF_TELEMETRY_URL=$(default_self_monitor_url "${REGION}")

# Generate config
API_SOCK_PATH="${SOCK_FILE}"

echo "Generating o11yagentd config (deploy_env=vefaas, site=${SITE}, region=${REGION}, control_plane_region=${CONTROL_PLANE_REGION})..."
# Add disk_io_throughput_limit param
generate_config "${BUNDLE_O11YAGENTD_DIR}" "${INSTALL_DIR}" "${SITE}" "${REGION}" "${DOWNLOAD_REGISTRY}" "${REMOTE_MANAGER_ADDRESS}" "${API_SOCK_PATH}" "${O11YAGENTD_DISK_IO_THROUGHPUT_LIMIT}" "${SELF_TELEMETRY_URL}"

# Optional: Override registry in CR
update_cr_registry_if_needed "${CR_REGISTRY}" "${INSTALL_DIR}"

# Inject VeFaaS metadata as environment variables for OneAgent
export O11YAGENT_ATTR_FUNC_ID="${_FAAS_FUNC_ID}"
export O11YAGENT_ATTR_FUNC_NAME="${_FAAS_FUNC_NAME}"
export O11YAGENT_ATTR_POD_NAME="${MY_POD_NAME}"
export O11YAGENT_ATTR_INSTANCE_ID="${MY_POD_NAME}"

echo "Starting o11yagentd in foreground with conf-dir=${CONF_DIR}..."
exec "${BUNDLE_O11YAGENTD_DIR}/o11yagentd" start --conf-dir "${CONF_DIR}"
